package com.example.jetjourney.dtos;

import com.example.jetjourney.enums.FlightStatus;
import jakarta.validation.constraints.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class ReservationDTO {

    private Long id; // No validation needed for ID (autogenerated by the database)

    @NotNull(message = "Flight ID is mandatory")
    private Long flightId; // Referencing the flight's ID

    @NotNull(message = "User ID is mandatory")
    private Long userId; // Referencing the user's ID

    @NotNull(message = "Reservation date is mandatory")
    private LocalDateTime reservationDate;

    @NotNull(message = "Status is mandatory")
    private boolean status; // true for Confirmed, false for Cancelled
}
